### ISSUE TITLE
ExecuteScript can only be called once 

### ISSUE THREAD

**Issue by merl111** [ngdenterprise/neo-test#16]
When a `TestApplicationEngine` is created and `ExecuteScript` is called, the `VMState` is set to `VMState.HALT` after successful execution, this means any additional calls will not be executed and there's no indication of that other than the `ResultStack` just containing the result of the first execution.

In the following example only the result of `function1` will be on the `ResultStack`
```C#

// first execution
engine.ExecuteScript<SomeContract1>(c =>  
        c.function1(arg1, arg2)                       
        );                                       
// second execution
engine.ExecuteScript<SomeContract2>(c =>  
        c.function2(arg1, arg2, arg3)                       
        );      
                                 
// at this point engine.ResultStack will only contain the result of `function1` 
// because `VMState` is set to `HALT` after the executiong and therefore all 
// incoming scripts are not executed anymore.

````

If one wants to call multiple contracts in the same context it needs to be done like this:

```C#
// create script for the first call
var script = (byte[])engine.Snapshot.CreateScript<SomeContract1>(c=>
        c.function1(arg1, arg2)                          
);                                                                         

// create script for the second call
var script = (byte[])engine.Snapshot.CreateScript<SomeContract2>(c=>
        c.function2(arg1, arg2, arg3)                          
);                       

// combine both
var combined = (Script)script.Concat(script2).ToArray();

// execute the combined script
engine5.ExecuteScript(combined);

```

Maybe there's a better solution, but that's what I am using now if I have calls that depend on each other, like a token transfer with a balance check afterwards.

**Comment by devhawk** [comment]
ExecutionEngine is not designed to handle multiple calls to `Execute`. But I can look into mechanisms for generating multiple invocations. Maybe something like this?

``` cs
var builder = new ScriptBuilder();
builder.CreateScript<SomeContract1>(snapshot, c => c.function1(arg1, arg2));
builder.CreateScript<SomeContract2>(snapshot, c => c.function2(arg1, arg2, arg3));

engine.ExecuteScript(builder.ToArray();
```

**Comment by devhawk** [comment]
Note, if you're adding multiple invocations of the same contract, you can pass multiple invocations to ExecuteScript/LoadScript/etc:

```cs
engine.ExecuteScript<Registrar>(
    c => c.register(DOMAIN_NAME, alice),
    c => c.register("DOMAIN_NAME", alice));
```
