### ISSUE TITLE
coverage collector not handling properly split class

### ISSUE THREAD

**Issue by vincentgeneste** [ngdenterprise/neo-test#55]
Our contract is split into subclass.

The coverage collector only reports the first match instead of all match, this looks like a bug in the way it processes raw coverage into the cobertura format

<img width="351" alt="Screen Shot 2023-03-06 at 5 36 38 PM" src="https://user-images.githubusercontent.com/25534589/223310742-4740512e-3194-45b9-9120-c1c2db3be72a.png">
<img width="609" alt="Screen Shot 2023-03-06 at 5 36 24 PM" src="https://user-images.githubusercontent.com/25534589/223310747-3c255237-050c-46b0-9205-402e065e3fe4.png">

**Comment by devhawk** [comment]
fixed by #57
